name: second workflow
on:
 push:
jobs:
  second:
    runs-on: self-hosted
    steps:
    - name: runs the first job
      run: echo "run's the first job"

    - name: run the second job
      run: echo "print run the second job"
     
